### ISSUE TITLE
Long delay between sending requests and getting a response/result

### ISSUE THREAD

**Issue by Enilo** [DIT112-V20/group-04#45]
# Description:
- When in Manual Control in the Android Application, sending requests to the car is very slow and causes a several second delay until the SmartCar starts moving and responds to commands.

# Expected behaviour:
- The SmartCar should immediatly respond to the sent commands

**Comment by krasen86** [comment]
The manual control was updated so that it sends fewer requests to the server. While working on the bug it was discovered that the main performance issue was caused by the sensor not by the request sending. The car can not handle the sensor readings and client requests. To increase the performance the logic was changed so there are fewer requests send. A new bug #63 was opened to resolve the sensor issue since this one was directed at the request sending/ receiving,
